import { Montserrat } from 'next/font/google';
import React from 'react';

import { Footer, Header } from '@/components/molecules';

import type { Metadata } from 'next';

import './globals.css';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <script
          defer
          data-domain="dinaprint.com"
          src="https://analytics.vicdev.com.es/js/script.js"
        ></script>
      </head>
      <body className={`${montserrat.className} text-font-primary`}>
        <Header />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
